Fix/Updates for debian documentation
Add information for building doxygen documentation
on debian and fix for hardcoded path for dot.

diff --git a/doc/dot b/doc/dot
--- a/doc/dot
+++ b/doc/dot
@@ -34,4 +34,13 @@ do
   fi
 done
 
-/usr/local/bin/dot ${ARGS}
+if [[ -x "/usr/local/bin/dot" ]]  
+then
+  /usr/local/bin/dot ${ARGS}
+elif [[ -x "/usr/bin/dot" ]]
+then 
+  /usr/bin/dot ${ARGS}
+else
+  echo "Program dot not found: See file doc/dot"
+  exit 1
+fi
